### ISSUE TITLE
~0.5-1 second delay before `handleDefocusGesture:` begins

### ISSUE THREAD

**Issue by oseparovic** [autresphere/ASMediaFocusManager#31]
I've noticed that there is a short delay between the doing a single tap gesture on the full screen to dismiss it, and the actual animation occuring. Is there any way that this animation delay can be removed or reduced?

Here is my `ASMediaFocusManager` initialization code:
```
self.mediaFocusManager = [[ASMediaFocusManager alloc] init];
self.mediaFocusManager.delegate = self;
self.mediaFocusManager.isDefocusingWithTap = TRUE;
self.mediaFocusManager.animationDuration = 0.3;
self.mediaFocusManager.elasticAnimation = NO;
self.mediaFocusManager.backgroundColor = [UIColor blackColor];
```

**Comment by autresphere** [comment]
Yes, you are right but there is nothing we can do about it. This is due to the fact the double tap is also supported (to zoom inside the image). Because of the double tap, the system must wait a little bit to decide whether the first tap is actually a single tap and not part of a double tap.
This is actually why the defocus with tap is an option and is not active by default here, as it "feels" a little bit slow.
